In [37]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split

In [38]:
dataSet = pd.read_csv('dataset.csv')
dataSet

Total Revenue  Total Cost
0         2408445.08  1811154.16
1         2153286.80  1344707.70
2         2045322.72  1768017.12
3         3048155.25  2634885.25
4          406257.50   231292.25
5         1072444.38   927041.98
6         2939051.46  2210170.92
7           32745.23    24624.46
8         1762353.20  1061483.23
9         3458689.20  2083203.63
10          49337.04    36592.96
11        2969462.40  1788537.36
12         783241.04   462288.12
13        1518261.30   896115.15
14        1843575.51  1486161.76
15        1209295.20   728370.78
16          36369.85    25218.15
17         941217.36   587781.54
18        1523180.19  1227881.44
19         155778.35   104366.57
20          50643.24    37561.76
21         385602.14   267369.06
22        5942291.25  4790260.00
23         298804.88   207185.52
24         436846.85   302901.15
25        3611709.20  2175369.13
26         694868.46   481808.34
27        5989178.37  4828057.12
28         840563.22   536796.96
29        1980685.30  1127652.19
...              ...         ...
49970      321141.60   215154.72
49971     3082328.34  2664425.14
49972        4226.49     3134.76
49973     4778130.50  3593161.00
49974       56607.18    36150.24
49975       24889.70    14170.31
49976     5493607.56  4428562.56
49977     1119147.52   698897.28
49978     6057199.28  4555022.56
49979      254821.56   220272.76
49980     4007375.20  2413682.78
49981     1265952.24  1020522.24
49982     1244900.22   795012.96
49983     1778529.60  1071226.44
49984     5316756.12  3998208.24
49985     1312139.20   819418.80
49986      457558.20   270062.10
49987     1198202.50   682165.75
49988        1091.61      809.64
49989     1910335.90  1087600.57
49990      719959.57   499206.03
49991      793904.76   597017.52
49992      197677.70   112542.71
49993      460027.75   308204.05
49994       80749.24    55989.96
49995     1396381.60   872027.40
49996     3778971.63  3046342.88
49997      137142.94    95092.26
49998      526729.60   172748.80
49999      613620.98   362174.19

[50000 rows x 2 columns]

In [39]:
dataSet.plot(x='Total Cost',y='Total Revenue',style='.')
plt.show()

In [40]:
x = dataSet.iloc[:,1].values
y = dataSet.iloc[:,:-1].values
x

array([1811154.16, 1344707.7 , 1768017.12, ...,   95092.26,  172748.8 ,
        362174.19])

In [41]:
x_train,x_test,y_train,y_test = train_test_split(y,x, test_size=0.2)
print('Training data\n',x_train)
print('Training data',y_train)
print('Testing data\n',x_test)
print('Testing data',y_test)

Training data
 [[3155315.31]
 [ 299963.79]
 [  20609.97]
 ...
 [1411035.54]
 [3612667.62]
 [ 641498.77]]
Training data [2727516.51  259294.59   15286.28 ...  832827.87 2716731.24  444802.83]
Testing data
 [[ 776516.73]
 [ 873734.19]
 [1280930.07]
 ...
 [ 565742.56]
 [3922733.22]
 [ 300439.48]]
Testing data [ 538421.67  755272.99 1032596.32 ...  185543.68 3390887.62  208318.92]


In [42]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)
print(regressor.intercept_)
print(regressor.coef_)

-89869.28489949193
[0.77272217]


In [43]:
y_pred = regressor.predict(x_test)
print(y_pred)

[ 510162.4078109   585284.49447194  899933.77851389 ...  347292.53377132
 2941313.64151071  142286.96206434]


In [44]:
df = pd.DataFrame({'Actual':y_test, 'Predicted':y_pred})
df

Actual     Predicted
0      538421.67  5.101624e+05
1      755272.99  5.852845e+05
2     1032596.32  8.999338e+05
3     3300079.81  2.860139e+06
4      812459.55  9.738030e+05
5      761708.76  8.526415e+05
6     1582754.60  1.324987e+06
7     4071076.54  4.093382e+06
8       53477.76 -3.415429e+04
9      930552.00  1.036094e+06
10      27749.20 -6.095920e+04
11    1194374.64  1.388006e+06
12    2421582.68  3.016853e+06
13    1548765.30  1.826517e+06
14     117909.11  4.612367e+04
15      59913.36 -2.744945e+04
16    1030099.56  1.308246e+06
17     563220.42  6.474990e+05
18     182210.56  3.394393e+05
19     905591.87  1.071942e+06
20     951209.28  1.061090e+06
21    1049071.38  1.333995e+06
22     287036.61  2.997146e+05
23    4566102.08  4.287003e+06
24       3861.36 -8.584639e+04
25     100929.27  2.260903e+04
26     570559.92  6.845300e+05
27     739897.41  8.788046e+05
28     243161.71  1.905864e+05
29     230890.77  1.764335e+05
...          ...           ...
9970      727.44 -8.891692e+04
9971  1358896.08  1.591579e+06
9972   297120.81  2.412502e+05
9973    57754.32 -2.969882e+04
9974  3695718.40  3.452690e+06
9975  1974899.52  1.803186e+06
9976   949664.94  1.085212e+06
9977   353285.62  2.731508e+05
9978   781858.56  8.561760e+05
9979   549642.33  5.226670e+05
9980  2492510.08  2.299345e+06
9981   213104.64  4.122293e+05
9982  2700919.20  2.499117e+06
9983   188824.44  1.205618e+05
9984  2175740.54  1.855069e+06
9985   629963.04  7.348785e+05
9986   111426.56  1.726642e+05
9987   897691.97  1.061807e+06
9988    78934.57  1.171566e+03
9989  4321995.68  4.053013e+06
9990   365346.58  2.855441e+05
9991  3499383.36  3.264491e+06
9992   218868.51  1.966734e+05
9993  2264947.78  2.237487e+06
9994   281308.16  5.729244e+05
9995    33856.35 -5.082035e+04
9996  2634885.25  2.265508e+06
9997   185543.68  3.472925e+05
9998  3390887.62  2.941314e+06
9999   208318.92  1.422870e+05

[10000 rows x 2 columns]

In [45]:
from sklearn import metrics
from sklearn.metrics import mean_squared_error,r2_score
print('MSE : ',mean_squared_error(y_test,y_pred))
print('RMSE : ',np.sqrt(mean_squared_error(y_test,y_pred)))
print('r2_stat : %.2f'%r2_score(y_test,y_pred))

MSE :  32371833789.522694
RMSE :  179921.74351512574
r2_stat : 0.98
